### ISSUE TITLE
Icon and Label issues Nautilus 

### ISSUE THREAD

**Issue by gizzmoguy** [Elbullazul/B00merang-Project#11]
The icons for Places (Document,Downloads,Music etc) in nautilus file manager are too close to labels am using Gnome 3.18.2 please fix.

**Comment by Elbullazul** [comment]
shure, please include a screenshot to have a look at the issue

**Comment by gizzmoguy** [comment]
Please find attached screen shot for previously mentioned issue  and bellow
are two other things i think you might want to improve on
I will also add screen shots all well

1)   toggle switches in menu like tweak tool have jagged lines

2)  and there are no boxes for check mark in contextual or pop up menus i
know it looks cleaner that way
    but it can get confusing especially when user is not familiar with an
application.

**Comment by Elbullazul** [comment]
@gizzmoguy can't see them.  Try dragging the screen shots in the comment section in the thread.

**Comment by gizzmoguy** [comment]
Ok here are the screen shots   i added some you can compare with yours to better understand what am trying to convey.
![screenshot from 1](https://cloud.githubusercontent.com/assets/17055240/13204623/d21a7a06-d8aa-11e5-9273-7f1530cd3623.png)
![screenshot from 2](https://cloud.githubusercontent.com/assets/17055240/13204625/d21b8306-d8aa-11e5-9b81-1e2f8a44da57.png)
![screenshot from 4](https://cloud.githubusercontent.com/assets/17055240/13204624/d21b1222-d8aa-11e5-82a2-550e0c006bee.png)
![screenshot from 5](https://cloud.githubusercontent.com/assets/17055240/13204626/d22f4968-d8aa-11e5-98ac-d8350918aa34.png)
![screenshot from 6](https://cloud.githubusercontent.com/assets/17055240/13204628/d2348e14-d8aa-11e5-9424-f46c828f5f37.png)
![screenshot from 7](https://cloud.githubusercontent.com/assets/17055240/13204627/d231bf9a-d8aa-11e5-8f57-a94404e58ff3.png)

**Comment by Elbullazul** [comment]
the checkboxes leave me perplex. I'll do some research to try to fix it

**Comment by cinnamoner** [comment]
@gizzmoguy 
I'm not familiar with Gnome Shell, but please tell me what theme is that you've put up for a comparison 'cause it looks very pro to me. Thanks.

**Comment by Elbullazul** [comment]
@gizzmoguy don't know how the bugs got fixed so quick! anyways, I'll upload a series of screenshots to show the corrections.
what's more, it doesn't influence the actual code since it works only with gnome 3.18

**Comment by Elbullazul** [comment]
![capture du 2016-02-21 19 18 44](https://cloud.githubusercontent.com/assets/15310985/13206754/de8a9104-d8d2-11e5-94ff-d3e6d6a0696c.png)
![fedora 23-2](https://cloud.githubusercontent.com/assets/15310985/13206755/dea37b7e-d8d2-11e5-9dc6-4e95471659b4.png)
![fedora 23](https://cloud.githubusercontent.com/assets/15310985/13206756/deae330c-d8d2-11e5-83c4-94999dfdbbea.png)

**Comment by gizzmoguy** [comment]
This looks absolutely awesome great job man really appreciate your work.
Could not keep silent about it. where do i download most updated version of
the theme. Saw that the latest commits were from 2 days ago thanks

**Comment by Elbullazul** [comment]
I've updated the code now. For an easier download, use the releases system : https://github.com/Elbullazul/Windows-10/releases/tag/v0.9.2

**Comment by gizzmoguy** [comment]
I and Downloaded the revised theme some of the issues are fixed but there
is still a problem with nautilus where the icon label are too close the the
icon itself  the version of nautilus is ver 3.18.5

**Comment by Elbullazul** [comment]
can you include a screenhsot of the problem please?

**Comment by gizzmoguy** [comment]
I was one that was discussed  days ago here is the screen shot
![screenshot from 2016-02-22 13-04-16](https://cloud.githubusercontent.com/assets/17055240/13225856/24e9cb32-d965-11e5-83c5-fc9c1893a056.png)

**Comment by Elbullazul** [comment]
so the patch didn't work?

**Comment by gizzmoguy** [comment]
No the did work hence why i sent you Nautilus version number was wondering
whether you had tried it on a different version of nautilus

**Comment by Elbullazul** [comment]
ooooooh, my bad, I just implemented the fix in the light theme
![image-my-bad](http://foro.refugioazul.cl/uploads/smiles/128758655.jpg)

upgrading in short...

**Comment by Elbullazul** [comment]
published the patched version : https://github.com/Elbullazul/Windows-10/releases/download/v0.9.2/Windows.10.Dark.v0.9.2.zip

**Comment by gizzmoguy** [comment]
Hey man the patch definitely worked but unfortunately i found two other issues they might be minor fixes but here they are 
.1) certain applications when click buttons there is no change in color or highlight to let you
know whether the feature is turn or off. Example Rhythmbox "Shuffle buttons and Repeat" you never know whether they are activated or not.

2) When the gnome shell dash Application Button is click it turns white and remain that way sometimes i will provide screenshot bellow 

![screenshot from 2016-02-22 18-31-37](https://cloud.githubusercontent.com/assets/17055240/13235326/bd86b228-d993-11e5-81dd-5ce5cd8a85e4.png)
![screenshot from 2016-02-22 18-32-53](https://cloud.githubusercontent.com/assets/17055240/13235327/bd8735ae-d993-11e5-994c-4ac1fa5cfe79.png)
![screenshot from 2016-02-22 18-34-27](https://cloud.githubusercontent.com/assets/17055240/13235328/bd87b272-d993-11e5-8235-5e833b0c7009.png)
![screenshot from 2016-02-22 18-36-01](https://cloud.githubusercontent.com/assets/17055240/13235329/bd9dbad6-d993-11e5-8ffe-01aa951b49d5.png)

**Comment by Elbullazul** [comment]
ok, I've adressed the rythmbox (and hopefully other apps) issue with the button stuff : 
![capture du 2016-02-22 19 30 23](https://cloud.githubusercontent.com/assets/15310985/13237554/e178410e-d99a-11e5-9877-522542412c43.png)

attacking the gnome dash issue, one that I've been wanting to fix for a looong time...

**Comment by Elbullazul** [comment]
ok, so I fixed this to better harmonize itself with the Cinnamon theme : 
![fedora 23-activities](https://cloud.githubusercontent.com/assets/15310985/13238486/5ae53064-d9a1-11e5-9650-a755b752b64b.png)

also, nautilus was actually the up-to-date version you use too : 
![fedora 23-works](https://cloud.githubusercontent.com/assets/15310985/13238487/5aeadf8c-d9a1-11e5-80b5-ed97b89a9a79.png)

thanks for your feedback!

**Comment by gizzmoguy** [comment]
So can you provide a download link fro the latest patches so i can test them Please ?

**Comment by Elbullazul** [comment]
I'll update to v0.9.3 today and I'll notify when release is ready

**Comment by gizzmoguy** [comment]
Cool 👍

**Comment by Elbullazul** [comment]
Sorry for the delay. He you go : https://github.com/Elbullazul/Windows-10/releases/tag/v0.9.3

**Comment by gizzmoguy** [comment]
I like the the changes you made to theme especially the desktop switch indicator all of the issues were addressed except am still getting Rhythm box shuffle selection problem i explained previously. I really appreciate your man and that's i can see at this time.
![screenshot from 2016-02-22 18-31-37](https://cloud.githubusercontent.com/assets/17055240/13285008/6de3a776-dace-11e5-9359-114beca90e6c.png)

**Comment by Elbullazul** [comment]
found the rebellious issue, a missing line of code : 
![fedora 23-hover](https://cloud.githubusercontent.com/assets/15310985/13288051/2d0be484-dad8-11e5-965c-2f339361ab24.png)

updating in short...

**Comment by gizzmoguy** [comment]
Great have you patched it into v0.9.3 yet? in yes let me know Thanks

**Comment by Elbullazul** [comment]
it's here : https://github.com/Elbullazul/Windows-10/releases/tag/v0.9.4

**Comment by gizzmoguy** [comment]
The theme is excellent. All Issues fixed.This is just my personal Taste can
you tell me how to get rid of the spinning "progress" indicator in the top
bar in gnome shell it happens when you lunch some application and not
others i know it not Bug/issue  i just want your help in getting rid of it
i just don't like the  inconsistency. thanks

**Comment by Elbullazul** [comment]
I'll investigate and answer you when I find a fix

**Comment by gizzmoguy** [comment]
Cool

**Comment by gizzmoguy** [comment]
Hello i was wondering whether you have a version of windows 10
transformation theme for testing on gnome shell 3.20 and if not whether you
are going to release it.

**Comment by Elbullazul** [comment]
@gizzmoguy I haven't yet,  but when I do I'll let you know
