### ISSUE TITLE
a way to set transparency

### ISSUE THREAD

**Issue by ghost** [Elbullazul/B00merang-Project#12]
gtk-main.css:
define a new color as rgba(red, green,  blue, 0)
in gtk-widget mix this color with its rgb only value to 0.9 or 0.1. and use it like a normal color definition.
works in muffin compton and compiz on 15.04 and on 16.04 too i guess...
not explaining more atm..
blur untested, a 7x7 box blur kernel is to cpu intensive.
target background toolbar menubar...
b.t.w not nice blocking user comments ..

**Comment by Elbullazul** [comment]
@bluedxca93 I froze the thread to avoid another "fight" (which I still don't understand)

I'm not the kind of guy to censor others, unless it messes things up more than improve them

BTW I'm working on a semi-transpanrent version of Glass, here's a sample : 
![capture du 2016-07-12 16-30-50](https://cloud.githubusercontent.com/assets/15310985/16782535/03376438-484e-11e6-96e3-e2fd5f2e3915.png)

**Comment by cinnamoner** [comment]
@Elbullazul 
And you never will. Don't invoke it again. As I've said: no more fighting. Period. Let it go.

**Comment by cinnamoner** [comment]
@Elbullazul 
I'm beholding it. Mindblowing.

**Comment by cinnamoner** [comment]
@Elbullazul 
Visit Gitter and thread 45 (W10 repo). Tension is no good. Feren and have reconciled. Call me nuts but that's the truth.

**Comment by ghost** [comment]
@elbullazul 
ok if its like that.
Am glad you know how to use transparent colors in gtk3.
@cinnamoner i.cant write on gitter so i do write still here. And posting that """issue/tip?""" here. is making sense in my opinion.

Don't misunderstand me but i have a set of themes i do port from time to time from older to newer version and do sometimes new too  that i invent from scratch sometimes but not in that speed you guys can do it.

**Comment by cinnamoner** [comment]
> I'm working on a semi-transpanrent version of Glass

@Elbullazul 
@bluedxca93 
I think this thread is about transparency. I might be wrong  but I see Nautillus in the screenshot. Do you think (semi)transparent window borders could somehow be achieved in Cinnamon as well?

**Comment by cinnamoner** [comment]
@Elbullazul 
I like your semi-transparent version of Glass a lot. Do you think you could expand it to Budgie as well. I don't want to overwhelm you with questions. Simple yes/no would suffice.

**Comment by Elbullazul** [comment]
@cinnamoner should work on budgie as well,  try it for yourself when v3 gone final,  I'm a bit short on time lately 

@bluedxca93 no use for gitter.im now that everything has gone fine.  I'll move interesting messages here in their appropriate threads

**Comment by cinnamoner** [comment]
> should work on budgie as well, try it for yourself when v 3h00 gone final

@Elbullazul 
Okay. Sounds good to me. Thanks.

@ Guys 
_Let us follow each others moves attentively before posting. That should prevent confusion._

**Comment by Elbullazul** [comment]
@cinnamoner I fear metacity (the window manager) will never support transparency fully :cry:

**Comment by cinnamoner** [comment]
> I fear metacity will never support transparency fully.


@Elbullazul 
Semi-transparency is much more adequate than full anyways. Countless examples have demonstrated that fact.

**Comment by ghost** [comment]
gconf apps gwd
dconf something compiz gwd
but this works only in metacity, compiz. but not on cinnamon.

**Comment by cinnamoner** [comment]
@Elbullazul 
So the name of the window manager in Cinnamon is Metacity? I never hide my ignorance.

**Comment by ghost** [comment]
@cinnamoner no its muffin, but muffin is based on mutter which is
based on metacity but enhanced by intel.

**Comment by cinnamoner** [comment]
@ Guys
And tell me whether at least semi-transparent window borders are achievable in Cinnamon.

**Comment by cinnamoner** [comment]
@bluedxca93 
Aha. I've just learned something. What about the 2nd question?

**Comment by cinnamoner** [comment]
@bluedxca93 
I have never been in clear with Metacity. I'm in clear with Kwin and Compiz though.

**Comment by cinnamoner** [comment]
@bluedxca93 
_Tell me whether at least semi-transparent window borders are achievable in Cinnamon._
 
     
cinnamoner commented 5 minutes ago

**Comment by cinnamoner** [comment]
@bluedxca93 
_And what's the name of the window manager in Gnome 3 and Budgie (obviously a fork of the former)_

**Comment by cinnamoner** [comment]
@bluedxca93 
Hey, I know these questions are silly. But I want to know.

**Comment by Elbullazul** [comment]
@cinnamoner GNOME 3 now manages windows itself through the CSD procedure (Client sided decoration) and SSD for old apps who supported metacity (say, firefox, gimp, etc.)

of course, I may be wrong, but that's how I see it

**Comment by ghost** [comment]
@cinnamoner
libmuffin is used in cinnamon but not the plain example muffin
binary.Transparency is theoretically possible, but not supported and
implemented now. And it surely has last place on the cinnamon feature
wishlist atm.

**Comment by cinnamoner** [comment]
@ Guys 
Hey, thanks for answering.

**Comment by Elbullazul** [comment]
@bluedxca93 which themes do you plan to port now?

**Comment by cinnamoner** [comment]
@Elbullazul 
I will delete this at once but trust me SHA256 is sufficient.

**Comment by cinnamoner** [comment]
@Elbullazul 
So you're basically telling me that Glass 3 should be semi-transparent on budgie windowborderwise, right?

**Comment by cinnamoner** [comment]
@Elbullazul 
May I ask you a question?

**Comment by cinnamoner** [comment]
@Elbullazul 
Can you make 2 zips both having the same checksum?

**Comment by Elbullazul** [comment]
@cinnamoner if they have the same content, yes

**Comment by cinnamoner** [comment]
@Elbullazul 
Think again.

**Comment by cinnamoner** [comment]
@Elbullazul 
Okay. Do an experiment right now.

**Comment by cinnamoner** [comment]
@Elbullazul 
Waiting for the result.

**Comment by Elbullazul** [comment]
You can do that yourself,  just compress some random folder two times and checksum both of them.

**Comment by cinnamoner** [comment]
@Elbullazul 
Have you done the experiment. This is no joke.

**Comment by cinnamoner** [comment]
@Elbullazul 
Experiment redone. Strange. This time round the metadata seems the same.

**Comment by cinnamoner** [comment]
> Check if source file date/time is different between compressions. If it is, you will never get the same checksum, as the metadada for the compresed file has changed.

@Elbullazul 
It seems I'm an annoying guy after all.

**Comment by cinnamoner** [comment]
> if they have the same content, yes

@Elbullazul 
So, the whole story is reducible to the following:
_Yes indeed one can create two or any number of zips sharing the same checksum if the content is identical, but not unless the metadata of that content is identical as well._
I guess by _content_ you've meant both _the content itself_ and _the metadata of that content_. I wasn't sure though. Simple as that.

**Comment by cinnamoner** [comment]
@Elbullazul 
I might know what you think but I was "(mis)leading the witness".

Yet another thing. There's only a theoretical benefit in SHA512 over SHA256, not a real-life one. Virustotal (a subsidiary of Google) never went any higher than SHA256. And believe me, Google takes checksumming very seriously.
Let me give you some further arguments:
1. I've never seen an iso (some are several Gigs in size) checksumed with SHA512.
2. A SHA512 is a rather long string and consequently uncomfortable to deal with for some.
3. Generating a SHA512 requires more computing, hence more power is absorbed, hence more pollution  generated, hence the planet is dying. Just kidding although there's some truth in it.
4. A SHA512, which is an obvious overkill, might attract malicious/joky intents.
5. One can't never be completely sure about a checksum (not even in a double-blind settup), unless it is personally handed over by the developer in flash and bones (and provided one knows him/her).
6. Checksums should always be taken with a pincha salt.


Neither of the two subjects belong here so just delete them.

**Comment by cinnamoner** [comment]
@Elbullazul
I'm in for a surprise or just waiting my time. Yes/No.

**Comment by cinnamoner** [comment]
Gonna have some coffee. Then if still no sign, I'll see you in fall. Stats.
At least Linus got his name back.

**Comment by cinnamoner** [comment]
@Elbullazul 
Whenever you're in mood again then.

**Comment by cinnamoner** [comment]
> I don't know whether you can see my point but the string wasn't incorrect. It was incomplete. Big deal.
There's a different between "incorrect" and "incomplete". If one changed it by 1 bit (the zip that is) there wouldn't be any similarity at all anymore. Seriously.

@Elbullazul 
7. In all likelihood, the event would never have happened with a SHA256.
Just a statistic extrapolation though.

**Comment by cinnamoner** [comment]
> duplicate 

@Elbullazul  I don't really don't know what you're talking about. Perhaps you referred to a _collision_. That is a rare event. I bet you'll never see such an event in your whole life.

**Comment by cinnamoner** [comment]
@Elbullazul 
This time 'round it's me who's flooding. Read it if you want to, then just delete it. Neither of those belong here. Thank you.

**Comment by cinnamoner** [comment]
8. In conjunction with the context, a SHA512 would put a smile on any expets's face. Some would even burst into laughter. We want people to take us seriously, don't we?

**Comment by cinnamoner** [comment]
Hey are you f with me?

**Comment by cinnamoner** [comment]
@Elbullazul
I rest my case.

**Comment by cinnamoner** [comment]
@Elbullazul 
I've just stopped on all threads. Let's continue what we're supposed to continue.

**Comment by cinnamoner** [comment]
@ All
The reference link from above leading to #47 is to be ignored. It had been misplaced. Sorry for the inconvenience.
