### ISSUE TITLE
XFCE 4.12 taskbar color doesn't match theme and XFCE taskbar text becomes unreable

### ISSUE THREAD

**Issue by ghost** [Elbullazul/B00merang-Project#16]
**Issue Type:** `Problem`
## DESCRIPTION:

XFCE taskbar changes to a dark navy blue color instead of matching the theme, furthermore, the taskbar's font changes to a similar color making it illegible. I'm running a clean installation of Debian 9 (*Stretch*) 64-bit with stock XFCE 4.12. This affects both B00merang Dark and B00merang Glass themes (*B00merang Green has the same issue with the XFCE taskbar and font being almost identically colored to the point of the taskbar becoming unreadable, but at least that's green*.)

I really need a nice dark black theme that works under GTK 3.22, so I'm hoping you can fix the only issue I'm experiencing with it so far. I'll attach pictures of the issue later when I can.

Thank you.

## SYSTEM:

**OS:** Debian 9 (_Stretch_) 64-bit
**DE:** XFCE 4.12
**GTK3 Ver.:** 3.22

**Comment by Elbullazul** [comment]
@SapphireTactician This bug has happened before with other themes, but it concerned the 3.18 version.
**Try adding [the following lines](https://raw.githubusercontent.com/B00merang-Project/Windows-10/master/gtk-3.0/apps/xfce.css) to the gtk-widgets.css file**. It's the 3.18 fix, and I think it could solve the issue.

If it does not, please post a screenshot of the bug

**Comment by ghost** [comment]
Sorry for the delay, I had some private issues that needed to be dealt with first.

>Try adding the following lines to the gtk-widgets.css file. It's the 3.18 fix, and I think it could solve the issue.

I appended the provided code to the end (*is that the correct part of the file to place the code? I don't know much about theming to be honest*) of the `gtk-widgets.css` file found in both the `gtk-3.0` and `gtk-3.20` folders. Still no joy.

>please post a screenshot of the bug

As requested:

B00merang Dark
![2017-06-27--104400_1600x900](https://user-images.githubusercontent.com/24427487/27595933-1600d08a-5b2c-11e7-8e4f-f9076c80b749.png)

B00merang Glass
![2017-06-27--104420_1600x900](https://user-images.githubusercontent.com/24427487/27595982-39077958-5b2c-11e7-8e7a-316b415993ce.png)

B00merang Green
![2017-06-27--104442_1600x900](https://user-images.githubusercontent.com/24427487/27596025-50906f76-5b2c-11e7-9250-50d7008311f5.png)

****

And as a reference picture, here's the same desktop with Adwaita Dark
![2017-06-27--104509_1600x900](https://user-images.githubusercontent.com/24427487/27596070-70a77890-5b2c-11e7-8606-88bd3525c4dc.png)

Also, in case you need more specific version information about my environment...

Terminal output for GTK component list and version numbers

```
ii  libgtk-3-0:amd64             3.22.11-1    amd64        GTK+ graphical user interface library
ii  libgtk-3-bin                 3.22.11-1    amd64        programs for the GTK+ graphical user interface library
ii  libgtk-3-common              3.22.11-1    all          common files for the GTK+ graphical user interface library
ii  libgtk-3-dev:amd64           3.22.11-1    amd64        development files for the GTK+ library
ii  libgtk2-perl                 2:1.2499-1   amd64        Perl interface to the 2.x series of the Gimp Toolkit library
ii  libgtk2.0-0:amd64            2.24.31-2    amd64        GTK+ graphical user interface library
ii  libgtk2.0-bin                2.24.31-2    amd64        programs for the GTK+ graphical user interface library
ii  libgtk2.0-common             2.24.31-2    all          common files for the GTK+ graphical user interface library
ii  libgtk2.0-dev                2.24.31-2    amd64        development files for the GTK+ library
```

**Comment by Elbullazul** [comment]
@SapphireTactician ooh, ok, there's probably a bad color definition somewhere

yes, DE-specific code should not be put in gtk-widgets.css, it's just a quicker instruction thant to tell you to make a file, paste the code there, add include file to gtk.css, etc.

**Comment by gps08** [comment]
@Elbullazul try the pull request that i have made

**Comment by Elbullazul** [comment]
@gps08 I can't merge if I haven't tested it, will check this soon

***

Tried and it does fix the issue, thanks a lot @gps08 will be merging soon

**Comment by ghost** [comment]
@Elbullazul Let me know when the fix is applied. Can't wait to use these.

**Comment by Elbullazul** [comment]
@SapphireTactician it should work properly now

also, I see you haven't installed the murrine-engine yet. If you want to get rid of those win95-looking controls, please install `gtk2-murrine-engine`

**Comment by ghost** [comment]
Awesome! It works beautifully now! Thank you SOOO much. I've been looking forward to enjoying these themes. Just don't forget to make a new release and update the gnome-look / opendesktop.org pages (*which is how I first discovered these themes*)

>also, I see you haven't installed the murrine-engine yet. If you want to get rid of those win95-looking controls, please install `gtk2-murrine-engine`

Oh? The theme has gtk2 engine dependencies? Alright, I took care of that. Good to know. You might want to mention that on the readme and themes' pages.

I didn't bother installing GTK2 theme engines on this machine at first because Debian 9's GTK based packages have almost entirely migrated to GTK3 from what I've seen. I also heard something about GTK2 not being supported soon.

**Comment by ghost** [comment]
Oh btw, I was really eyeing the Windows 10 Dark theme too, so hopefully you can fix this issue on all your other themes that may be affected by this bug - haven't tested it yet but I don't see a recent commit there so I'm assuming it might be affected still. Thanks again.

**Comment by Elbullazul** [comment]
@SapphireTactician the Windows 10 themes were once affected, but I=by a different issue: it was backwards of what you just had, the panel was right but the other parts were wrong 😄 

yep, would be a good idea to write the dependencies in the readme
