### ISSUE TITLE
Desktop Icon font alignment is off

### ISSUE THREAD

**Issue by ghost** [Elbullazul/B00merang-Project#17]
We fixed one problem but somehow created another. The font for desktop icons is no longer centered under the icon.

Old Version:
![old](https://user-images.githubusercontent.com/24427487/27595933-1600d08a-5b2c-11e7-8e4f-f9076c80b749.png)

Current Version:
![2017-06-28--132405_1600x900](https://user-images.githubusercontent.com/24427487/27651383-22967482-5c06-11e7-9fef-fca8a51ed691.png)

Adwaita Dark (*again for reference*):
![2017-06-28--132737_1600x900](https://user-images.githubusercontent.com/24427487/27651432-4b0e9390-5c06-11e7-90d6-226cf6bed870.png)

**Comment by Elbullazul** [comment]
@SapphireTactician sorry for the goof, I'm working without testing changes (no Xfce available)

the problematic code seems to be this snippet:

```
# Xfce-desktop text settings
style "xfdesktop-icon-view" 
{
	XfdesktopIconView::label-alpha = 0

	#Text colors you can delete these if you want you use gtk theme colors
	fg[NORMAL] = @fg_color
	fg[SELECTED] = @fg_color
	fg[ACTIVE] = @fg_color
}
widget_class "*XfdesktopIconView*" style "xfdesktop-icon-view"
```

can you remove it and post the result?

**Comment by ghost** [comment]
Removed the code snippet from `gtkrc` in the `gtk-2.0` folder. (*Took me a while to find which file it was hiding in. I never dug through the guts of a theme before so I have no idea where certain pieces of code belong*) Still no joy. Problem persists, please advise.

**Comment by Elbullazul** [comment]
@SapphireTactician remove the panel style:
```
style "panel"
{
	xthickness = 0
	ythickness = 0

	bg[NORMAL]	= @base_color
	bg[ACTIVE]	= @base_color
	bg[PRELIGHT]	= @base_color
	bg[SELECTED]	= @base_color

	fg[NORMAL]	= @fg_color
	fg[PRELIGHT]	= @fg_color
	fg[ACTIVE]	= @fg_color
	fg[SELECTED]	= @fg_color

	text[NORMAL]	= @fg_color
	text[PRELIGHT]	= @fg_color
	text[ACTIVE]	= @fg_color
	text[SELECTED]	= @fg_color
}
```

**Comment by ghost** [comment]
Removed the code snippet, as advised, from `gtkrc` in the `gtk-2.0` folder. Problem persists, plus bug regression.

![2017-06-28--140336_1600x900](https://user-images.githubusercontent.com/24427487/27652747-d57be736-5c0a-11e7-8a12-8b82bf0ffe12.png)

:(

**Comment by Elbullazul** [comment]
@SapphireTactician well, at least we found the code that made the panel change...

what about removing the darktree style?

**Comment by ghost** [comment]
Still no joy... could it be GTK3 theme related and not GTK2?

**Comment by Elbullazul** [comment]
don't think so, since it happened just after the push

if you remove all the text after the block
#########################
#XFCE-specific styles and colors#
#########################

does it still not work?

**Comment by ghost** [comment]
....still broken. I even rebooted too just in case somehow the "fixes" don't apply from simply swapping themes.

**Comment by Elbullazul** [comment]
then it's something to do with the theme itself that didn't apply when murrine-engines was not installed. 

I'll check this later, I need a VM to see and experience with changes and fixes

**Comment by hauntingEcho** [comment]
If it helps, mine is left-aligned for files with names only one line long, but centered for longer filenames (XFCE on Stretch, definitely GTK2 - it reacts to those colors changing)

![screenshot_2017-07-01_00-43-47](https://user-images.githubusercontent.com/1661988/27759438-a1356298-5df6-11e7-8077-ab8b43deb405.png)

**Comment by hauntingEcho** [comment]
oddly enough, the text-shadow is centered though
![screenshot_2017-07-01_00-46-56](https://user-images.githubusercontent.com/1661988/27759447-d4cfbfea-5df6-11e7-9354-0106691ce918.png)

**Comment by Elbullazul** [comment]
@SapphireTactician can you post how the desktop looks with the Win10 Dark theme? it has different Xfce code so it may fix this issue

**Comment by Elbullazul** [comment]
@SapphireTactician @hauntingEcho I'm going to see how it behaves on the latest Xfce available in Manjaro. Will post updates as soon as I find a fix

**Comment by Elbullazul** [comment]
@SapphireTactician @hauntingEcho maybe this will fix the bug. Allegedly it already did for graybird and arc, so...

https://gist.github.com/Elbullazul/93ecf38df61f7537ae33db31b985d1b3

paste the code in the gtkrc file instead of the old xfce code submitted on the older commits

**Comment by Elbullazul** [comment]
last 3 commits should fix this

**Comment by hauntingEcho** [comment]
I'm seeing the text left-aligned still after catching up to master:

![screenshot_2017-07-11_19-43-42](https://user-images.githubusercontent.com/1661988/28096816-627b152e-6671-11e7-8e72-57f86eeaa4fc.png)

**Comment by hauntingEcho** [comment]
and still only for one-line file names:

![screenshot_2017-07-11_19-47-33](https://user-images.githubusercontent.com/1661988/28096917-085b74fc-6672-11e7-8bed-185bce6150c4.png)

**Comment by hauntingEcho** [comment]
actually, it looks like this is an issue with murrine that was fixed in 0.98.2 (I'm currently on 0.98.1):
https://bugs.launchpad.net/ubuntu/+source/gtk2-engines-murrine/+bug/1598316
https://github.com/horst3180/arc-theme/issues/607

thanks for your patience though!

**Comment by hauntingEcho** [comment]
@SapphireTactician you're on Debian as well right?

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=831678

**Comment by ghost** [comment]
Ugh, I can't even "Franken-debian" to fix it as even Sid's repo still uses the affected version. From what the link in @hauntingEcho 's reply states, disabling text shadows in the theme is a known workaround. @Elbullazul Perhaps we should go with that until Debian issues 0.98.2?

**Comment by Elbullazul** [comment]
@SapphireTactician the latest master has the same changes Arc pushed to their repo. I haven't tried but it's supposed to work (reboot needed)

**Comment by ghost** [comment]
Can confirm upstream gtk2-engines-murrine fixes the problem. Finally, I can enjoy these themes! :D 

Lord knows when Debian will adopt it though, because Debian... you might want to apply the workaround (*disabling text shadows*) in the meanwhile because it'll probably be less hassle than instructing everyone on how to get and install the latest Murrine engine from outside of their distro.

**Comment by Elbullazul** [comment]
@SapphireTactician but I did, I haven't tried it though

**Comment by ghost** [comment]
Ooooh... I misread, when you said latest master, I thought you meant for the theme engine, so I updated theme engine. Doh! Let me rollback the theme engine and see what happens.

**Comment by Elbullazul** [comment]
@SapphireTactician it works allright:

![virtualbox_xubuntu 17 04_12_07_2017_18_07_21](https://user-images.githubusercontent.com/15310985/28141995-0949b1b0-672d-11e7-88b1-1e23ee6b597e.png)

**Comment by ghost** [comment]
@Elbullazul Then why did it break when I rolled back to gtk2-engines-murrine 0.98.1.1-6 (*latest version Debian has*) ? :(

![2017-07-12--181420_1600x900](https://user-images.githubusercontent.com/24427487/28142232-fb23c070-672d-11e7-8644-0dc29673ad16.png)

I think the only solution might be to manually install 0.98.2 from outside of Debian's repos :-/ It was fine when I extracted the new engine version from the Arc tarball, but that's a messy thing to ask of regular users. Sigh.

**Comment by Elbullazul** [comment]
@SapphireTactician I guess most people will not be using a rolling distro. And if they do, they know what kind of bugs they could run into.

on the stable channels all works OK, only Debian seems affected (didn't test arch)
