### ISSUE TITLE
[GTK3] slider color missing

### ISSUE THREAD

**Issue by hauntingEcho** [Elbullazul/B00merang-Project#18]
Thanks for all the recent updates!  I am still having issues with sliders not displaying (Debian Stretch, GTK 3.22.16-1).  Comparison screenshot to Adwaita Dark (using pavucontrol - the Pulse Audio mixer) and terminal output below (Adwaita had no output)

![screenshot_2017-06-28_19-59-32](https://user-images.githubusercontent.com/1661988/27667088-c785ce52-5c3d-11e7-9249-720cf11fe9cf.png)
`
>GTK_THEME=B00merang\ Dark pavucontrol

(pavucontrol:13254): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:4:37: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:13254): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:5:37: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:13254): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:6:31: The style property GtkButton:default-border is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:13254): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:7:30: The style property GtkButton:image-spacing is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:13254): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:8:29: The style property GtkButton:inner-border is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:13254): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:9:31: The style property GtkWidget:interior-focus is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:13254): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:10:36: The style property GtkButtonBox:child-min-height is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:13254): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:11:40: The style property GtkButtonBox:child-internal-pad-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:13254): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:13:36: The style property GtkCheckButton:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:13254): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:14:38: The style property GtkCheckMenuItem:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:13254): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:16:32: The style property GtkExpander:expander-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:13254): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:19:33: The style property GtkMenu:horizontal-padding is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:13254): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:20:31: The style property GtkRange:stepper-spacing is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:13254): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:21:29: The style property GtkRange:trough-border is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:13254): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:22:37: The style property GtkRange:trough-under-steppers is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:13254): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:25:37: The style property GtkScrollbar:min-slider-length is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:13254): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:27:48: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:13254): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:28:31: The style property GtkStatusbar:shadow-type is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:13254): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:189:30: The style property GtkWidget:focus-padding is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:13254): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:190:33: The style property GtkWidget:focus-line-width is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:13254): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:935:30: The style property GtkButton:image-spacing is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:13254): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:936:29: The style property GtkButton:inner-border is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:13254): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1085:32: The style property GtkMenuItem:arrow-scaling is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:13254): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1286:30: The style property GtkNotebook:initial-gap is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:13254): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1287:30: The style property GtkNotebook:has-tab-gap is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:13254): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1707:35: The :prelight pseudo-class is deprecated. Use :hover instead.

(pavucontrol:13254): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3013:33: The style property GtkWidget:focus-line-width is deprecated and shouldn't be used anymore. It will be removed in a future version

(pavucontrol:13254): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3630:15: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(pavucontrol:13254): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3649:15: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'
`

**Comment by hauntingEcho** [comment]
it looks like this may only effect sliders created a certain way - the ones in xfce4-keyboard-settings are fine (no console output)

![screenshot_2017-06-28_20-34-25](https://user-images.githubusercontent.com/1661988/27667583-5f284976-5c41-11e7-987c-5634e7d0e2e7.png)

**Comment by Elbullazul** [comment]
@hauntingEcho the 'good sliders' are GTK2, so it's not related to the issue

I think it's missing a class refernce to set margins; will check that when I get more time, but should not take very long

**Comment by Elbullazul** [comment]
does 8345d9e fix this?

**Comment by ghost** [comment]
>does 8345d9e fix this?

@Elbullazul  Can confirm. 👍  Works on my end, although it's always been a little difficult to see the "knob" / "dial" for lack of better words.

![2017-06-29--122432_1600x900](https://user-images.githubusercontent.com/24427487/27699034-f1a5c2da-5cc6-11e7-877d-65c640830262.png)

Of course everything else is still broken though. :P

**Comment by hauntingEcho** [comment]
That fixed it - thanks!
