### ISSUE TITLE
Distorted horizontal scrollbar in FireFox ESR 52

### ISSUE THREAD

**Issue by ghost** [Elbullazul/B00merang-Project#19]
Idk what possessed me to check this but um.... yeah. Just see for yourself:

![2017-06-29--123707_1600x900](https://user-images.githubusercontent.com/24427487/27699327-e6a46a3e-5cc7-11e7-8876-49f3c1127beb.png)

Could apply to other applications too, but I haven't tested any other applications that use that style scrollbar. Still getting Debian 9 configured (*as I decided it'd be less messy to do a clean install instead of an upgrade from Debian 8*), so I don't have a full production environment yet.

*Edit: Just realized I found that with the version before the slider fix commit (*as I switched back to restore sanity to my taskbar*). Going to check again with the slider fix in place*

*Update: Still broken even after the slider fix commit*

**Comment by hauntingEcho** [comment]
can confirm (Firefox ESR 52.2.0 64-bit)

![screenshot_2017-07-01_00-54-50](https://user-images.githubusercontent.com/1661988/27759504-080bef90-5df8-11e7-9edb-a7f4d8b702ce.png)

**Comment by Elbullazul** [comment]
@SapphireTactician @hauntingEcho ran into this issue the other day, thought I had fixed it, but probably didn't push the patch, and now it's overwritten :/

will fix soon

**Comment by Elbullazul** [comment]
sorry guys, I'm busy porting the compiling structure to SCSS, but I will commit a temporary fix. After scss I will then tacke the desktop font thing

**Comment by hauntingEcho** [comment]
looks good!  thanks so much!
