### ISSUE TITLE
Bad Colors when saving files in google-chrome

### ISSUE THREAD

**Issue by diegogvieira** [Elbullazul/B00merang-Project#2]
When you are prompted to save something in google-chrome, the colors are too dark, sample: http://imgur.com/WgnT6XC

I guess that colors should be white for text

The same happens when using ctrl + F in google-chrome: 
http://imgur.com/nTrMB2M

Look at the right-top corner, you barely see the text.

Thanks for opening this github repo, great work!

**Comment by Elbullazul** [comment]
Thanks for your feedback, that was issued after another person experienced problems with text in firefox and I built an 'easy fix', but now I'll see this issue with greater attention.

**Comment by Elbullazul** [comment]
Dark v0.7.6b fixes this

**Comment by diegogvieira** [comment]
Maybe is just me, but I cannot open the file :(

**Comment by Elbullazul** [comment]
https://github.com/Elbullazul/B00merang-Project/blob/master/Windows%2010%20Themes/Windows%2010%20Dark%20v0.7.6b.zip?raw=true
