### ISSUE TITLE
Start Menu showing up shifted a few pixels to the right, in Cinnamon.

### ISSUE THREAD

**Issue by Zerophase** [Elbullazul/B00merang-Project#5]
I don't know if this is up to the theme. In Cinnamon the Start Menu pops up shifted a few pixels to the left. I think it might be ideal to have it pop up at the edge of the taskbar.
![startmenu](https://cloud.githubusercontent.com/assets/4284284/11305008/2b9ce854-8f70-11e5-9d6b-5405400a4ad0.png)

**Comment by Elbullazul** [comment]
Hi,

It is impossible to make it stick to the edge of the taskbar, the closer I can get it to go is a padding of 27 px, but it still looks closer. I would recommend using a third-party menu applet if you can, but thanks for reporting this issue; v0.8 will include the correction.

**Comment by Zerophase** [comment]
Yeah, it looks like other themes aren't perfectly flush with the edge of the screen. They're a bit further to the left though.

**Comment by Elbullazul** [comment]
I found its something about the arrow radius. I've fixed it, but may not update till Sunday...
