### ISSUE TITLE
Why Mediafire for Icons?

### ISSUE THREAD

**Issue by MichaelTunnell** [Elbullazul/B00merang-Project#6]
Mediafire links aren't typically permanent so I'm just curious why the icons pack was not release here on github like the themes.

**Comment by cinnamoner** [comment]
Hi Michael,

Good point. Icon packs should be uploaded to Git (for a lot of reasons). Not to this repo though. In a different repo. This repo should only point to that other repo. But all in all, I vote for your suggestion.

Another thing: downloadable content (of any kind) should be provided with checksums. I suggest MD5 and SHA1. Or even better: SHA512 (MD5 and SHA1 are now obsolete).

Thank you for your input. This place is however for bugtracking only. So I was told by the developer and we should respect that.

**Comment by cinnamoner** [comment]
Hi again,

Upon reading your comment all over again, it seems to me that it might have a rhetorical touch to it. No more comments from me here, except those strictly referring to what this place was intended for. Cinnamoner out.

**Comment by Elbullazul** [comment]
Hi @MichaelTunnell.

Well, the icons were uploaded by a now inactive user in gnome-look. and I dare not to take his artwork as my own. There has been a guy who has reuploaded them here : http://gnome-look.org/content/show.php/Win10+Icons+Pack?content=174349

I have no idea if I should put them here...

**Comment by MichaelTunnell** [comment]
@cinnamoner I was not being rhetorical and your other comments were good points as far as checksums. Thanks for the input.

@Elbullazul I think there should be a long term link to provide to people because the mediafire link could vanish at any time. I don't think it would be a problem to offer a mirror of the icons as long as you give credit to the author. If you provide credit then that should be enough.

**Comment by Elbullazul** [comment]
Sure, I had no idea mediafire content would expire after some time. I'll reupload to some stable mirror in short.

Thanks to both of you for your invaluable feedback, @MichaelTunnell @cinnamoner

**Comment by MichaelTunnell** [comment]
Well the good news is that MediaFire changed their policies, it used to be "delete files after 90 days of no downloads" now they have a 1 year login policy. If you do not login at least once per year then they will delete the files. [policy](http://knowledgebase.mediafire.com/article.php?id=100)

**Comment by Elbullazul** [comment]
Thanks for letting me know. I'll be a bit less worried about the icons...

**Comment by MichaelTunnell** [comment]
I still suggest putting them up on github anyway, or at least make a page on your website that keeps track of everything that way I can link to one page for it all.

**Comment by Elbullazul** [comment]
My web host wants me to pay, says it's too big.

Maybe I can upload them in this repo, since I started this new one for Windows, and soon will relocate all themes in this repo

**Comment by MichaelTunnell** [comment]
> My web host wants me to pay, says it's too big.

Less than 18MB is too much? Well that sounds like the worst host ever...that is very very small and it is complaining about that? That is a pathetic host.

I have hosting accounts with gigantic files even full backups of like 10GBs so less than 18MB being too much is sad.

---

Anyway, yea you should just upload the icons to GitHub and maybe even the Windows 10 theme repo...I mean it kind of fits there afterall.

**Comment by Elbullazul** [comment]
Yeah, it makes sense. Their up now : https://github.com/Elbullazul/Windows-10/tree/master/Windows%2010%20Icons

**Comment by MichaelTunnell** [comment]
Looks great to me, they should also be included in the releases and then I think it would be perfect and ready for the article.

Edit: just checked the Release and you already did that so that's great! :)

**Comment by Elbullazul** [comment]
Great! Can you post the article link here please? When it's done, shure xD
