### ISSUE TITLE
Suggestion: Utilize GitHub Releases

### ISSUE THREAD

**Issue by MichaelTunnell** [Elbullazul/B00merang-Project#7]
I really like the effort in this theme so I am writing an article that will be featuring it to explain how to make their Linux Desktop look like Windows 10 via this theme but the current way of getting downloads can be confusing to some.

I'd suggest utilizing the Release System that  GitHub provides so that people can share the Release page of the repo and all of the latest archives can be included in the one link.

What do you think?

**Comment by Elbullazul** [comment]
I would love to use github to its maximum potential. Unfortunately, I haven't found advanced tutorials of the Git software. Would you like to help?

**Comment by MichaelTunnell** [comment]
> Would you like to help?

Sure, I can help but if you want to learn here are some links.

> I haven't found advanced tutorials of the Git software.

You don't actually need to use Git in order to make releases, GitHub has a system for doing it on the website.
- Creating Releases: https://help.github.com/articles/creating-releases/

I also linked a cheat sheet below for Git which should come in handy because it helped me learn Git when I first started using it.
- Git Cheat Sheet: https://training.github.com/kit/downloads/github-git-cheat-sheet.pdf

Here is a good example of what it could look like when using the release system.
- Sample Release repo: https://github.com/xPoke/MetroMumble/releases/

---

I'd also suggest releasing in with a data system so the version of the packages can be different.

Release 2015-11-23:
- Windows 10 v0.7.9
- Windows 10 Dark v0.7.9
- Windows 10 KDE v0.3.0
- OS X El Capitan v0.3c

This way they can still all have different version numbers based on changes but only have one release per group.

---

Another option is to separate the themes so each theme has their own Repo. This is what I would prefer.

**Comment by Elbullazul** [comment]
Thanks for the suggestions! I'll have a look then tomorrow

**Comment by MichaelTunnell** [comment]
Actually, I am building a new repo structure for you right now so if you want to check it out. Here is the Windows 10 default theme.

I actually changed the name from Windows 10 Default to Windows-10-Light so it makes it more obvious the Light vs Dark theme stuff.

I haven't changed everything so if you want to keep the name change you would need to look through what needs to be adjusted but the repo structure would be the same regardless.

https://github.com/MichaelTunnell/Windows-10-Light

If you want to use this structure then I can just hand control over to you and you'd have ownership on it.

---

I'm also building a repo for Windows-10-Dark and the OS X theme you made so if you like the first structure I can roll it out to the other two.

---

Here is what a Release for the repo structure would look like. https://github.com/MichaelTunnell/Windows-10-Light/releases/tag/windows-10-light

**Comment by Elbullazul** [comment]
Looks great! I gave it a try and had this as a result : https://github.com/Elbullazul/B00merang-Project/releases/tag/0.7.9

what do you think?

**Comment by MichaelTunnell** [comment]
The release looks great but I would also remove the archives from the repo normally and then put the source code in folders at least if you want the repos to be containing all of the themes.

**Comment by cinnamoner** [comment]
Hi Guys,

Let me emphasize again: a master archive.iso could come in handy as well. Nothing more than a suggestion.

**Comment by MichaelTunnell** [comment]
I think a .iso would not provide much benefit, besides GitHub already provides a master archive download.

https://github.com/Elbullazul/B00merang-Project/archive/master.zip

Although changing the structure of the repo is something I still want which would also improve the master archive.

**Comment by cinnamoner** [comment]
Think about burning it to a DVD. Some still like this kind of local storage. Master zip is comprised of many zips into a zip. I'm just considering catastrophic failure. .iso might not be so prone to that, not to mention that one has easier access to any version zip. Also, the burning is "optimized". Yeah or Nay?

**Comment by cinnamoner** [comment]
OKAY. There are some ambiguities in my formulation but I believe you can still figure out what I mean. I admit that it might not be of much relevance. One can still do it if he or she so desires.

**Comment by cinnamoner** [comment]
Upon thinking about it, my suggestion seems superfluous anyways. Can forget it. Just carry on.

**Comment by Elbullazul** [comment]
I understand your thinking @cinnamoner, nonetheless, I don't know why someone would like to burn the whole archive since the themes included there aren't of any relevance.

**Comment by cinnamoner** [comment]
I find the whole history of the theme relevant, not just the latest and greatest. Cloud is good and statistically safer. However some of us still like to have tangible media. In some instances local storage should not be abandoned. Consider me new and old school put together. Just as I said, the whole issue hardly bears any significance. I can make an image if my heart so desires. I'd say it is pointless to discuss a personal whim any further.
Since you had the courtesy to address me, I take this opportunity to make a suggestion: Cinnamon, Mate, XFCE. I take the risk of repeating myself: Other Stuff's "My opinion on" series about DEs might be a good guideline on where to concentrate efforts. And yeah, you rank highest in my preferences for theme creators. Not likely to change.
Also, you mentioned something about including new things into 0.8. I assume your referred to artwork, maybe icons or the like. Whatever your intention, please don't include Cortana. Joking.

**Comment by cinnamoner** [comment]
Why would collectors collect anything? I'm also a collector of digital history. Simple as that.

**Comment by MichaelTunnell** [comment]
> I find the whole history of the theme relevant, not just the latest and greatest. Cloud is good and statistically safer.

I agree that a history of the project would be nice but it doesn't need to be here on the repo, they could all be in Release form or just stored somewhere else altogether.

> However some of us still like to have tangible media. In some instances local storage should not be abandoned. Consider me new and old school put together. Just as I said, the whole issue hardly bears any significance. I can make an image if my heart so desires. I'd say it is pointless to discuss a personal whim any further.

Agreed, the people who want such a thing can make such a thing or just burn the Zips to a disc via Brasero or K3B.

> Since you had the courtesy to address me, I take this opportunity to make a suggestion:

Please, don't do that. You can just create your own issue thread to address another topic. This is one of the reasons forums get messy because people try to change the point of a thread at times.

It is always better to create a new thread or a new issue if the content you want to discuss is unrelated to the main topic at hand.

**Comment by cinnamoner** [comment]
"Please, don't do that."
OK. Sorry. I apologize.

**Comment by Elbullazul** [comment]
You mean, having something like this ? https://github.com/Elbullazul/Windows-10

Release is off too : https://github.com/Elbullazul/Windows-10/releases

**Comment by MichaelTunnell** [comment]
Exactly! That's perfect. The source is easily available and forkable so it is easier for people to contribute to the theme. (provided they are familiar with Git)

**Comment by cinnamoner** [comment]
Hi Guys,

Let me tell that I like it too how it's been organized.

**Comment by MichaelTunnell** [comment]
> Let me tell that I like it too how it's been organized.

👍

**Comment by Elbullazul** [comment]
Hi,

My intention isn't to cause you extra work, but could you post a link to the article when finished? I would like to have a look at it :)

**Comment by MichaelTunnell** [comment]
@Elbullazul I will absolutely link it when I finish it. Unfortunately, it won't be as soon as I hoped as I have other articles and some client work to do. I will link it as soon as it publishes though.

**Comment by cinnamoner** [comment]
@MichaelTunnell 
Article or no article, only recently have I fully realized how important your input to this project had been and how immensely primitive and ignorant I used to be (and might still be comparatively to a future version of myself). I've encountered you in other places as well. You really know your stuff. Thank you, Michael.

**Comment by MichaelTunnell** [comment]
> Article or no article

It's coming . . . though sadly it has taken a lot longer than I intended. I actually started a YouTube channel which unexpectedly took a huge amount of my time. http://tuxdigital.com/yt

> only recently have I fully realized how important your input to this project had been and how immensely primitive and ignorant I used to be (and might still be comparatively to a future version of myself).

Thanks for the compliments. Everyone is ignorant of everything until they become informed. I constantly fight my ignorance and still I'll never truly be where I want to be solely due to it being impossible. :)

> I've encountered you in other places as well.

If you remember, where might those places be? I'm just curious.

> You really know your stuff. Thank you, Michael.

Thanks for the kind words. You're welcome and I'm glad I could help.

**Comment by cinnamoner** [comment]
@MichaelTunnell 
I've just subscribed to tuxdigital. Interesting. I wonder whether you would review the Budgie Remix. My name is Richard Addison aka cinnamoner. At this moment in time my favorite distros are: Mint 18 Cinnamon, the Budgie Remix and Manjaro Cinnamon community build. Obviously, I'm not trying to push anything. Thanks for helping us out on the checksum issue. I think Christian's work is bleeding-edge and unprecedented in its field.

**Comment by cinnamoner** [comment]
@MichaelTunnell 
Check this out. A KDE distro. I would like an opinion and a review on tuxdigital, if you think it's worth it. At any rate, I won't settle for anything less than an opinion. You're the KDE man. I can't think of anyone more qualified in KDE. If your opinion on the distro will be positive, then I might add it to my collection which presently encompasses Mint 18 Cinnamon and Manjaro Cinnamon 16.06.1.
Hey, KDE has always seemed too intricate to me, but is certainly any tweaker's dream.
https://distrowatch.com/table.php?distribution=blackpanther
Looking forward ...
Best regards,
Richard

**Comment by cinnamoner** [comment]
@feren You might check it out as well, hmmm? If I were to choose a DE capable of window border transparency, It would probably be KDE. It uses Kwin for a window manager, if I recall correctly.
Okay, there goes the link again:
https://distrowatch.com/table.php?distribution=blackpanther

**Comment by dominichayesferen** [comment]
Err, Cinnamoner, Compiz (with Metacity) is also capable of Windows transparency now remember?

**Comment by dominichayesferen** [comment]
@MichaelTunnell 
Do a Pull Request with the new structure?

**Comment by cinnamoner** [comment]
> Compiz

Sure feren. I would use it in Xfce, Mate, Budgie. I wasn't talking about Compiz though. I was talking about  Kwin in conjunction with KDE. Check that distro and give an honest option. Please & thank you.

**Comment by dominichayesferen** [comment]
@cinnamoner 
KDE does look good now and then, and I've used it once or twice before in KDE 4 and KDE 5... Well, at least Vistar7 (I think that's what It's Called) still works mostly in KDE 5 (excuse the minor eye-saw from Breeze brightness here and there... :/)

**Comment by cinnamoner** [comment]
@feren Just go to YouTube and watch a video of that distro. Then we'll speak again. Sorry, I must check out now. I've got an urgent thing to attend :)

**Comment by dominichayesferen** [comment]
@cinnamoner 
Before you do, get a life that's not all crude... _facepalm_

SERIOUSLY

**Comment by cinnamoner** [comment]
@MichaelTunnell 
@Elbullazul 
@feren 
@bluedxca93

For your convenience 

http://youtu.be/zdwSI7oUzRA

**Comment by dominichayesferen** [comment]
@cinnamoner 
Ok, you've got me talking... Man, the customizations half have inspired me a little bit (especially the Vivaldi ones, there again, my one has custom thumbnails on Speed Dial unlike their's) (also, no English site for it)

Fact: If Cinnamon didn't exist, feren OS would be on KDE Neon by now...

**Comment by cinnamoner** [comment]
@feren Yeah, Vivaldi always makes you sing. Thanks.

**Comment by cinnamoner** [comment]
@feren Yes man, there's an English site to it. Go there from the Distrowatch link provided upstream.

**Comment by cinnamoner** [comment]
@feren Tho one thing I'm not sure though yet is whether it's a 32 or 64 or 32 PAE.

**Comment by cinnamoner** [comment]
@MichaelTunnell KDE Neon is on par with Cinnamon in my eyes. Both are great.

**Comment by dominichayesferen** [comment]
@cinnamoner 
Good, only saw the website of it on the video that you posted here... (which had their language on)

**Comment by cinnamoner** [comment]
@feren 
I don't know what it's based on. Distrowatch says Mandriva but that ain't correct. It only has some features from the late Mandriva. It's not Debian-based, it's not Arch-based, perhaps Ubuntu-based? Or perhaps it's an independent base, like Solus? I don't know. I do know that it's using RTM packages though. Does it have it's own repo? Driver management can be done from Ubuntu. It's not a massive download but I'm still not in clear with a few things.

**Comment by cinnamoner** [comment]
@feren And what model? It doesn't seem to be rolling. Perhaps LTS point release?

**Comment by dominichayesferen** [comment]
@cinnamoner 
I don't know to be honest... But the description though says this: "...originally forked from Mandriva Linux, but which **is now under independent development**" (Though, in blackPanther, by the looks of it, just point-release)
(Though, if you're talking about KDE Neon, Kubuntu-based)

**Comment by cinnamoner** [comment]
@feren There's a somewhat better description on Softpedia. I like the installer as well. It's called ... be back. They have been around for years. I'll do some research. Downside: no real community support.

**Comment by dominichayesferen** [comment]
@cinnamoner 
1. Ubiquity (Ubuntu Installer)
2. Calamares (Highly configurable installer mainly used in Arch distributions)
3. Something else...

**Comment by cinnamoner** [comment]
@feren Okay, here's the result of my digging:

Distribution name: 	BlackPanther OS
Latest Version: 	16.1
Code name: Silent Killer
Release date: 06 August 2016
Desktop environment: KDE Plasma
Base distribution: Independent
Home page: 	http://www.blackpantheros.eu
Packages: Linux Kernel 4.7.0, Qt 5.6.1, Plasma + (components) 5.7.1/5.24.0/16.04.3, Python 3.5.1, Calamares installer.

Additional Info:
1) BlackPanther is an independently evolved GNU/Linux distribution.
2) Development started in 2002.
3) First stable release of BlackPanther OS in 2003.
4) Since then the project has been releasing new versions on a yearly bases.
5) The project adopts best design practices from all popular GNU/Linux distributions to provide the best user experience.

Hmmm. Sounds good to me. I might even invite the developer for a conversation.

**Comment by cinnamoner** [comment]
![01 plymouth theme](https://cloud.githubusercontent.com/assets/15638605/17788361/f3d56cdc-6595-11e6-94d7-369c791f2731.jpg)
Plymouth

**Comment by cinnamoner** [comment]
@MichaelTunnell What do you think of it?

**Comment by ghost** [comment]
@cinnamoner ubiquity is a great application.

**Comment by cinnamoner** [comment]
@feren It seems its community is on Facebook. Too bad. I hate Facebook. It's the worst crowd-control software to date.

**Comment by cinnamoner** [comment]
@bluedxca93 Thanks for jumping in. If the base is independent, like Solus's, I wonder who provides the security updates. Okay, the developer has a list of collaborators, I just wonder whether it's secure enough.

**Comment by ghost** [comment]
@cinnamoner build-/convert it from arch-linux to their unique
packaging system. I dont say it directly but slitaz and puppy import
code from ubuntu and arch linux. ubuntu imports debian and sometimes
arch and fedora/opensuse packages. of course its always hidden and
sometimes import only security patches.

**Comment by cinnamoner** [comment]
@bluedxca93 Okay, thanks.

**Comment by dominichayesferen** [comment]
@cinnamoner 
Did you find out what installer it was or at least found a 'How to install' video so that I could see if I could identify the installer?

**Comment by dominichayesferen** [comment]
@cinnamoner 
Looking at Darkness's installer, I have no idea what installer that thing is (isn't Calamares nor is it any Ubiquity)

**Comment by MichaelTunnell** [comment]
@cinnamoner:

> I wonder whether you would review the Budgie Remix.

I am going to be reviewing [Solus](https://solus-project.com/), origin of Budgie. Is there something uniquely different for Budgie Remix that makes it worth reviewing alongside Solus?

> I would like an opinion and a review on tuxdigital, if you think it's worth it. At any rate, I won't settle for anything less than an opinion. You're the KDE man. I can't think of anyone more qualified in KDE.

I appreciate the vote of confidence. I wouldn't consider myself the "KDE man" solely because I don't want to limit my channel to any one DE or any one distro. My intention is to focus on any and all things Linux.

However, I will give it a look. It seems that it only runs on i586 so I would need a 32bit machine. Unfortunately, I only have 64bit machines so I can only review it via Virtual Machine.

>  Hey, KDE has always seemed too intricate to me, but is certainly any tweaker's dream.

I like KDE Plasma not because it is a "tweaker's dream" in fact I didn't start using KDE until I was done with being a tweaker. I just want the system I use to do what I tell it to and not fight me all the time. GNOME, Unity, Cinnamon, XFCE, MATE, etc are all fighters in some way. KDE Plasma just says "do it this really weird way that no one else does? alright, cool dude. Let's do that."

---

@feren:

>  Do a Pull Request with the new structure?

I'm not sure what you are referring to. This thread is super old. Essentially, my suggested restructuring was already adopted and then @cinnamoner decided to hijack the f**\* out of this thread. :)

---

@cinnamoner:

> His been shapeshifting a lot lately. He used to be Linux help guy. Then turned into Windows help guy. Now he's English Bob. Whatever, great commentator, with a unique style.

He ended his previous channels yelling at the Linux community for being hostile and hateful. He wasn't a saint himself though.

Anyway, I don't really like his videos because he doesn't really do much research before recording. That's a pet peeve of mine for most Linux YouTubers though. They act as an authority but they spend so little time on what they are discussing that they have no authority on the topic. Maybe he's changed though, I haven't watched his latest stuff.

---

@cinnamoner:

> KDE Neon is on par with Cinnamon in my eyes. Both are great.

I like Cinnamon but it has glaring issues like the dependency on solid GPU or on-board graphics. This makes it not viable at all for minimalism. KDE on the other hand is actually incredibly minimal depending on the hardware it is put on. I am making a YouTube video to prove this.

---

@cinnamoner:

> Distrowatch says Mandriva but that ain't correct. It only has some features from the late Mandriva. It's not Debian-based, it's not Arch-based, perhaps Ubuntu-based? Or perhaps it's an independent base, like Solus? I don't know. I do know that it's using RPM packages though. Does it have it's own repo? Driver management can be done from Ubuntu. It's not a massive download but I'm still not in clear with a few things.

Based on means many things. This is why I don't really like DistroWatch, they use terms that aren't very descriptive. If you go to the distrowatch page for Mandriva it says they had a release today. However, Mandriva went defunct last year so not likely.

It's probably a fork of Mandriva from some point long ago like Mageia did.

---

@feren 

>  (Though, if you're talking about KDE Neon, Kubuntu-based)

KDE Neon is not based on Kubuntu, it is directly based on Ubuntu. The first release of KDE Neon was Kubuntu based but that was completely beta and never intended to be permanent solution. As for 16.04, KDE Neon switched to their more permanent method of basing directly on Ubuntu. KDE Neon and Kubuntu share the same base and DE but they are vastly different.

**Comment by dominichayesferen** [comment]
@MichaelTunnell 
1. Oh okay... (I obviously remember from the first BETA of KDE Neon)
2. Pull Request's are when you request a certain amount of changes to the target repository, this can be done by comparing the target repository to a fork of it that you would then have made, or can be compared with other methods, if the owner accepts the pull request or a collaborator does, the differences to the target repository compared with the fork (or other means) are given to the target repository as a commit to the repository...

**Comment by cinnamoner** [comment]
@MichaelTunnell Thank you. Much appreciated.

**Comment by dominichayesferen** [comment]
@MichaelTunnell 
What I've noticed different about Budgie Remix:
1. Panel on the left
2. That panel acts like a dock (kinda)
3. Based on Ubuntu
4. Different Wallpapers
5. Means you can get Arc in the Ubuntu Repositories because why not...

**Comment by cinnamoner** [comment]
@feren Perhaps you've noticed. Just a couple of years ago, Mint was regarded as the best balance and rolling models were feared by the mainstream user comming over from Windows. Things have changed though. Windows 10 is a rolling model and a handful of rolling Linux distros are quite reliable and secure.  Perhaps it's just me but the new best balance is Manjaro. I would even try Apricity OS. The later, along with AntergOS are Arch made easy to install. For what it's worth, I sure like the wallpapers in Apricity. But hey, Majaro is more suitable for my taste. They also hold back the packages a little longer (about 2 week of delay relative to Arch). Another factor in my leaning for Manjaro is that I never really liked Mint depending on the Ubuntu base. Sure it's a versatile base but it's produced by Canonical. I guess that says it all. It feels good to see there's serious alternative and no shortage of fallback distros. I'm continuing to think Mint is awesome. They are fiercely holding out against a wave of criticism. Their strength and weakness paradoxically have the same source.

**Comment by ghost** [comment]
@cinnamoner ubuntu is a good codebase and its relatively easy to turn
off unity features.

**Comment by cinnamoner** [comment]
@MichaelTunnell I like the plasma desktop. I'm actually thinking about downloading Manjaro KDE as I'm writing. My only reluctance is comming from the widespread  (but perhaps unjustified) rumour according to which the plasma desktop is overly resource hungry.

**Comment by cinnamoner** [comment]
> ubuntu is a good codebase 

@bluedxca93 Never doubted that. I'm just saying it's good to see viable alternative.

**Comment by cinnamoner** [comment]
@feren There are 3 distros featuring the Budgie desktop:
1. Soulus. The very builders of Budgie. Release model: point. Soon: shift to rolling model. Independent base. Downside: rather scarce app base atm.
2. Budgie Remix. Featuring the Budgie desktop. Ubuntu base with all the goodies. LTS, point model. Probably the best looking. And the most versatile.
3. Manjaro Budgie. Rolling model. Well put together. Arch base.

**Comment by dominichayesferen** [comment]
@cinnamoner 
Solus, not Soulus

**Comment by ghost** [comment]
@cinnamoner
b.t.w
debian  is a great time machine in fact its the only distribution not
deleting old releases completly on all sites. It helps if you need
gtk1 libc5 gcc3 or gimp 1.5.similar outdated packages and or
compilers.

**Comment by cinnamoner** [comment]
Rolling is a relative term. It can't really be applied generically. It boils down to the distro.

**Comment by dominichayesferen** [comment]
Well since this discussion is turning into a Linux Discussion, shall we move to the old 'Discussion about feren OS' issue (whilst I change the name to reflect all distros)?

**Comment by cinnamoner** [comment]
@feren I'll rectify the typos. It's a draft. 
@bluedxca93 Debian is great but not so versatile.

**Comment by dominichayesferen** [comment]
Ok, I renamed it to reflect any discussions on this (now not related to the title) issue, and you can find it here as always:
https://github.com/Elbullazul/Windows-10/issues/45

PS: @Elbullazul Shall you mark this Discussion invalid or change the title since the discussion kinda tooken an unexpected turn towards Linux Talk instead of the repos?

**Comment by cinnamoner** [comment]
Deepin is great as well. It's just that I can't cure my addiction to a startmenu.

**Comment by dominichayesferen** [comment]
Deepin is one of the reasons that a Rolling release feren OS would be Debian based (probably some time when Zuro UI looks like the concepts of it, feren OS will become RR)

**Comment by cinnamoner** [comment]
Also, resource hungry is a generic concept. I'll reread it and make some adjustments.

**Comment by cinnamoner** [comment]
@feren I'm shutting down the desktop. The drive is already full of isos. No download today. I'm on tablet, so we can continue on the other threads.

**Comment by MichaelTunnell** [comment]
@feren:

> 1. Pull Request's are when you request a certain amount of changes to the target repository

I'm aware. This thread is no longer relevant to the original suggestion and my original suggestion was 10 months ago and was adopted by the project just a few days later.

@feren:

> What I've noticed different about Budgie Remix:
> 1. Panel on the left
> 2. That panel acts like a dock (kinda)
> 3. Based on Ubuntu
> 4. Different Wallpapers
> 5. Means you can get Arc in the Ubuntu Repositories because why not...

1 and 2 - ok but not noteworthy in my opinion for a video.
3 - cool but no video needed.
4 - alright, people use default wallpapers? Is that really still a thing?~
5 - that's cool but I'd rather use a PPA or a Snap for themes or just manually install it myself because the Ubuntu Repos are super slow.

---

@cinnamoner:

> Perhaps it's just me but the new best balance is Manjaro. I would even try Apricity OS. The later, along with AntergOS are Arch made easy to install.

I can't agree with that because Manjaro is not 100% compatible with Arch or the AUR as they change a lot including the kernel. It could work great but it can also blow up in the user's face as it already has for even silly reasons such as forgetting to renew an SSL Cert . . . twice.

Antergos is 100% Compatible because it uses mostly just Arch packages. Antergos only provides their own packages when Arch doesn't provide them or they are custom to Antergos.

Note: it's not AntergOS, it's Antergos. Antergos is a Galician word that means "Ancestors".

@cinnamoner:

> They also hold back the packages a little longer (about 2 week of delay relative to Arch). Another factor in my leaning for Manjaro is that I never really liked Mint depending on the Ubuntu base.

That delay results in absolutely nothing. They do not do any additional testing, it only slows down the updates. It also can potentially result in conflicts like when they have left back a few packages for over a month and multiple months in some cases. 2 Weeks Delay = pointless.

@cinnamoner :

> I never really liked Mint depending on the Ubuntu base. Sure it's a versatile base but it's produced by Canonical. I guess that says it all.

That only says that you're judgmental but it doesn't say why. Why does it bother you that Ubuntu is produced by Canonical?

---

@bluedxca93:

> ubuntu is a good codebase and its relatively easy to turn off unity features.

It's a fantastic code base and using Ubuntu's Minimal ISO means it doesn't even start with Unity so nothing to remove. :)

---

@cinnamoner:

> My only reluctance is comming from the widespread (but perhaps unjustified) rumour according to which the plasma desktop is overly resource hungry. 

KDE Plasma is not resource hungry in any way at all and thus 100% unjustified. This is typically said by people like you who are just repeating what they've heard or by people who for some reason purposefully spread misinformation.

I used to be on the side you are on in repeating what I had heard. I thought the same as you for years. I decided to genuinely try out KDE Plasma in late 2013 / early 2014 and it's been my favorite DE ever since. I took a laptop from 2008/2009 (don't remember) and put KDE Plasma on it because I was sick of Cinnamon being so freaking slow. I actually tried everything else before Plasma and then I finally said "screw it . . . how bad could it get".

I expected it to be super slow and bloated like people always say . . . it's not even remotely slow or bloated and it performed beautifully on that laptop, even better than all the others WITH Effects and Animations ON! I became a KDE fan that day.

@cinnamoner:

> Soon: shift to rolling model.

Already shifted to Rolling.

@cinnamoner:

> Rolling is a relative term. It can't really be applied generically. It boils down to the distro.

While true, some distros are both. Debian is both "Stable" and Rolling.

@feren:

> change the title since the discussion kinda tooken an unexpected turn towards Linux Talk instead of the repos?

That is literally what I warned @cinnamoner about [8 months ago](#issuecomment-160333183). ;) This thread was dormant for 7 of those months actually. I'll close the thread after this reply.

**Comment by cinnamoner** [comment]
@MichaelTunnell Thank you Michael. I'm now slightly less ignorant than I used to be just a couple of day ago. I've just learned again from you. Ultimately, that has been the purpose of it all. I'll probably open a fresh thread about Gtk vs Qt.

**Comment by cinnamoner** [comment]
@MichaelTunnell
Like it or not, first encounter typically happens on YouTube. Most of those people are not reviewers at all. As you've pointed out, they barely document themselves, if at all, and they're just processing one distro after another as in a canned bean factory. Yeah sure they splash up a disclaimer stating it's not a review, just their first impression. Well, most of those impressions are damaging and unfair. I can only imagine how frustrating all that is for someone trying to do the right thing. Unfortunately most people prefer an easy meal and not the truth (if there's such a thing at all) which takes some effort to be digested.

About the Ubuntu base. It's produced by a corporation. I don't dislike it from a technical perspective but from an ideological perspective. Although one of my aims in life is to free myself from all ideologies, none of us can claim to be entirely free of them. Let's have something clear: I don't hate corporatism at all. Without it, there wouldn't be any progress at all. Corporatism is a natural and necessary phase in humankind's evolution. But that doesn't mean I don't dream of a society where money is no longer the driving force. I pretty much endorse Stallman's vision. You may think that I'm naive and an idealist. I assure you I'm neither. I'm as coldly pragmatic as a human can possibly be.

About the Plasma desktop. I never noticed Cinnamon to be sluggish but I did have this feeling that it's struggling behind the scene a bit. I'll surely try Plasma. It's the only way I can from an objective opinion. I never used to like KDE. I've always felt it overbloated with unnecessary features and aesthetically unpleasant. That untill the advent of Plasma 5. I still think it's is bloated but I'll ignore the features I'm not interested in. I'm really curious to see how snappy it is compared to Cinnamon. Michael, I'm no fanatic. I want to give Plasma a fair chance. Not because it's your favorite. Because I want it to be my favorite.

**Comment by cinnamoner** [comment]
Yeah, let's have something "Gnome-free" for a change. An almost impossible endeavour as even Plasma is generous enough to accommodate the infamous GTK, along with its Qt.

**Comment by Elbullazul** [comment]
@cinnamoner can you discuss this topic in a new thread please? Let's try to keep the repo structured

**Comment by cinnamoner** [comment]
> can you discuss this topic in a new thread please? ...

@Elbullazul I'm done. I'm only interested in the W10 and Vista themes.

@feren You're sure thumbuping heavily, my friend 👍

**Comment by cinnamoner** [comment]
> can you discuss this topic in a new thread please? ...

@Elbullazul I'm done. I'm only interested in the W10 and Vista themes.

@feren You're sure thumbuping heavily, my friend.

**Comment by dominichayesferen** [comment]
@cinnamoner 
I think you accidentally posted the same comment twice
PS: Do you know why those actually are in Git? (From what I've seen, they're used like Disqus's upvote and downvote buttons to show support or the complete opposite towards an issue comment and/or comment...)

**Comment by dominichayesferen** [comment]
@cinnamoner 

> I'm shutting down the desktop. The drive is already full of isos. No download today. I'm on tablet, so we can continue on the other threads.

If you have them, just DISCARD the Alpha, Beta, RC, etc ISOs (but not Stable) once Stable comes out in a little bit into the future (It's literally done, just now prepping the site for the launch of 2016.2, last minute checks, etc)

**Comment by cinnamoner** [comment]
> PS:  Do you know why those actually are in Git? (From what I've seen, they're used like Disqus's upvote and downvote buttons to show support or the complete opposite towards an issue comment and/or comment...)

@feren Hey, yeah, I've reached the same conclusion.

**Comment by dominichayesferen** [comment]
@cinnamoner ...or at least, I think that's how it works... ;)

**Comment by dominichayesferen** [comment]
@cinnamoner BTW, before I go back to the other Conversation repo, here's the WIP site that will replace 'Home' upon the launch of feren OS 2016.2 Stable:
http://ferenos.weebly.com/20162hometesting.html <

**Comment by cinnamoner** [comment]
>If you have them, just DISCARD the Alpha, Beta, RC, etc ISOs (but not Stable) once Stable comes out in a little bit into the future (It's literally done, just now prepping the site for the launch of 2016.2, last minute checks, etc)

@feren Okay, done. Do you think one pass of overwrite is enough? 😉

**Comment by cinnamoner** [comment]
@feren Okay, I've got it, let's respect Elbullazul's wish and quit the thread.

**Comment by dominichayesferen** [comment]
@cinnamoner 

> Okay, done. Do you think one pass of overwrite is enough?

Depends on the agenda...

**Comment by dominichayesferen** [comment]
ok, _thread now abandoned_
