### ISSUE TITLE
Issue with Cinnamon --replace

### ISSUE THREAD

**Issue by Zerophase** [Elbullazul/B00merang-Project#9]
Whenever I run `Cinnamon --replace` to add updates to my desktop session I keep getting these errors.

> (cinnamon:4800): St-WARNING **: Failed to load /usr/share/themes/Windows10/cinnamon/menu-background.png: Error opening file: No such file or directory
> 
> (cinnamon:4800): St-WARNING *_: Did not find color property '-arrow-background-color'
> (cinnamon:16283): St-WARNING *_: Failed to load /usr/share/themes/Windows10/cinnamon/favorites-background.png: Error opening file: No such file or directory
> 
> (cinnamon:16283): St-WARNING **: Did not find color property '-gradient-start'
> 
> (cinnamon:16283): St-WARNING **: Did not find color property '-gradient-end'

**Comment by Elbullazul** [comment]
Ok, will fix those errors. I guess they come from an older project I once tried (buy failed)

Easy to fix

**Comment by cinnamoner** [comment]
Hi Guys,

Just dropped in to say that I would really like those fixed. Thank you Zerophase for pointing them out.
When to expect 0.8.1, if I may?

**Comment by Elbullazul** [comment]
For Christmas? xD

I'll fix them before this afternoon, but no new version, kind of a service pack (?)

**Comment by cinnamoner** [comment]
Hi again,

It actually occurred to me, once I had inquired about 0.8.1, that a fix would be a better choice at this time. Kinda service pack as you put it. Yeah, that would do just fine. Please load it up and give some sort of instro on how to use it (just a few words). And that would be a wrap for 0.8., but not until Zerophase actually confirms that said fix addresses each and every issue pointed out by him. So in a nutshell, waiting for the fix and confirmation from Zerophase that all those have been successfully addressed by the fix, service pack, whatever. Zerophase represents a standard to me. OKAY. Waiting said service pack to show up (the sooner the better). Thank you. Waiting ...

**Comment by cinnamoner** [comment]
Zerophase,

Please check again, high and low, narrow and wide, to see if you can find more. I don't want a service pack no. 2 for 0.8. Thank you and I value your input.

**Comment by cinnamoner** [comment]
Don't wanna be a nuisance but no service pack yet.

**Comment by Elbullazul** [comment]
Some problems while rebuilding and had to restart corrections. Not going to take long...

**Comment by cinnamoner** [comment]
OKAY. Thank you. Please consider testing the theme on Mint Cinnamon 17.3. Might have already.

**Comment by cinnamoner** [comment]
Well, Zerophase, the much talked-about Service Pack has been delivered ...

**Comment by Elbullazul** [comment]
I have no idea of the _gradient-start/end_ issue. I just see a bunch of **none** arguments

**Comment by Zerophase** [comment]
It might be a bug on Cinnamon's end. Give me a sec to update.

**Comment by Zerophase** [comment]
Hey, could you update the zip to your site. I'm having a hard time getting my script to download correctly from gnome-look. Thanks.

**Comment by Elbullazul** [comment]
Updated

**Comment by Zerophase** [comment]
Alright, I don't see the bugs anymore.

**Comment by Elbullazul** [comment]
Glad it works now.
